base-org/op-viem

src/actions/public/getL2HashesForDepositTx.test.ts
src/actions/public/getWithdrawalMessages.test.ts
src/actions/public/getWithdrawalMessages.ts
src/decorators/publicOpStack.ts

This is needed for withdrawal proofs

add method to getWithdrawalMessages from an L2 transaction hash

---

src/actions/public/getL2HashesForDepositTx.test.ts
src/actions/wallet/writeUnsafeDepositTransaction.test.ts
src/actions/wallet/writeUnsafeDepositTransaction.ts
src/decorators/walletOpStack.ts
src/utils/getDepositEventsInfoFromTxReceipt.ts

There was an issue with the types for `writeUnsafeDepositTransaction` was not allowing `value` to be passed. I solved this by making the types less generic, which I think is good. 
```
WriteContractParameters<
typeof optimismPortalABI,
'depositTransaction',
TChain,
TAccount,
TChainOverride
>
```
Note: now value is required to be passed. We should think about how to distinguish the args.value from the top level value. The latter being the amount that will be minted on L2, the former being the mint that will be sent as msg.value in the call

fix types for unsafeDeposit and add test

---

src/actions/public/L1/getL2HashesForDepositTx.ts
src/utils/getDepositTransaction.test.ts
src/utils/getDepositTransaction.ts
src/utils/getL2HashFromL1DepositInfo.ts
src/utils/getTransactionDepositedEvents.test.ts
src/utils/getTransactionDepositedEvents.ts

In this PR I 
- Rename 
- getDepositEventInfoFromTxReceipt→ getTransactionDepositedEvents
- getDepositTransactionFromTransactionDepositedEvent →  getDepositTransaction
- Allow source hash to not be passed to getDepositTransaction and compute as needed

simplify naming, and better ergonomics

---

src/actions/public/L1/getL2HashesForDepositTx.test.ts
src/actions/public/L1/getL2HashesForDepositTx.ts
src/actions/public/L2/getWithdrawalMessages.test.ts
src/actions/public/L2/getWithdrawalMessages.ts

In testing, I came across an issue where this method erred that it could not find the tx
I considered changing this to have like a wait param or something, but it seems simpler just to allow this function to also just take the receipt and then the waiting can be down out of band.

allow getL2HashesForDepositTx to take tx receipt

---

src/actions/public/L2/getProveWithdrawalTransactionArgs.test.ts
src/actions/public/L2/getProveWithdrawalTransactionArgs.ts

Viem was complaining that it was not 32 bytes

fix output root proof version in getProveWithdrawalTransactionArgs

---

package.json

Add only-allow utility which will throw an error if someone accidentally installs with a package manager other than pnpm

chore: Add only-allow

---

src/utils/resolveL1OpStackContractAddress.test.ts

Interested to get feedback on this one. Could be more elegant I think.
Would like @roninjin10's eyes on it.
Update: Can't get the type error to go away unless I provide the `address` param yet the function resolves every address I've given it so unsure how to mock the `L2ChainOrAddressError`.

:white_check_mark: chore: add `resolveL1OpStackContractAddress` test

---

CHANGELOG.md

Fixes incorrect release versions in `CHANGELOG.md`.

:wrench: Fix CHANGELOG

---

site/.vitepress/config.mts

* Organizes the actions in alphabetical order ([viem.sh](https://viem.sh/docs/getting-started.html) also uses alphabetical ordering of actions) 
* Creates and adds missing pages to index (will implement those once this is merged; plenty of empty pages already exist)
* Fixes a typo in the sidebar for `simulateWithdrawERC20`
Let me know if we prefer another name to the `General` category under `Utilities` for functions like `resolveL1OpStackContractAddress`.

:memo: docs: organize config.mts

---

.changeset/honest-cows-deliver.md
src/actions/public/L1/getL2HashesForDepositTx.ts
src/actions/public/L2/getWithdrawalMessages.ts

Not using the functions extended from `client` allows for bundlers to tree shake more effectively

Fix getTransactionHash to use un-decorated function for better tree shaking

---

site/.vitepress/config.mts
site/docs/actions/public/L1/getL2HashesForDepositTx.md
site/docs/actions/public/L1/getOutputForL2Block.md
site/docs/actions/public/L1/getSecondsToFinalizable.md
site/docs/actions/public/L1/getSecondsToNextL2Output.md
site/docs/actions/public/L1/readFinalizedWithdrawals.md
site/docs/actions/public/L1/readProvenWithdrawals.md
site/docs/actions/public/L1/simulateDepositERC20.md
site/docs/actions/public/L1/simulateDepositETH.md
site/docs/actions/wallet/L1/writeDepositERC20.md
site/docs/actions/wallet/L1/writeDepositETH.md
site/docs/utilities/deposits/getL2HashFromL1DepositInfo.md
src/actions/index.ts

The following actions have been added to the docs:
* `getSecondsToFinalizable`
* `readFinalizedWithdrawals`
* `readProvenWithdrawals`
Along with some other minor cleanup.
Resolves #82

📝 docs: add `read*` functions with cleanup

---

.changeset/eighty-weeks-sort.md
site/.vitepress/config.mts
site/docs/actions/wallet/L1/writeDepositTransaction.md
site/docs/actions/wallet/L1/writeSendMessage.md
src/_test/live.test.ts
src/actions/index.ts
src/actions/wallet/L1/writeDepositTransaction.test.ts
src/actions/wallet/L1/writeDepositTransaction.ts
src/decorators/walletL1OpStackActions.ts

We realized that there is actually no issue of lost ETH using this call. In the EOA caller case, it is credited to their L2 balance and they can move this balance via an L2 call or another L1 depositTransaction. 
In the smart contract wallet case, it is credited to an alias of their L1 address, and they can move this balance via a new depositTransaction call from L1.

Remove "unsafe" from depositTransaction

---

site/docs/actions/public/L1/simulateDepositETH.md
site/docs/actions/wallet/L1/writeDepositETH.md
src/actions/public/L1/simulateDepositETH.test.ts
src/actions/public/L1/simulateDepositETH.ts
src/actions/wallet/L1/writeDepositETH.test.ts
src/actions/wallet/L1/writeDepositETH.ts
src/types/depositETH.ts
vitest.config.ts

updating `writeDepositETH` to use `writeDepositTransaction` on the `OptimismPortal` contract instead of `depositETHTo` on the standard bridge
- updated `writeDepositETH` to use `writeDepositTransaction`
- updated args to reflect contract
- added a test
- updated docs

chore: update writeDepositETH to use writeDepositTransaction

---

src/actions/index.ts
src/actions/public/L2/estimateFees.test.ts
src/actions/public/L2/estimateFees.ts
src/actions/public/L2/estimateL1Fee.test.ts
src/actions/public/L2/estimateL1Fee.ts
src/actions/public/L2/estimateL1GasUsed.test.ts
src/actions/public/L2/estimateL1GasUsed.ts
src/decorators/publicL2OpStackActions.ts
src/index.ts
src/types/gasPriceOracle.ts
src/utils/transactionSerializer.ts

- Copy paste gas estimation actions from https://github.com/ethereum-optimism/optimism/blob/develop/packages/fee-estimation/src/estimateFees.spec.ts
- Changed naming conventions to match op-viem
- deleted some of the more niche actions like `version` and `l1BaseFee`. The recommended way to use this is to just use the gasPriceOracle contract or get stuff like l1BaseFee from l1 they just bloat the API including them here imo

:sparkles: feat: Add gas estimation actions

---

package.json

Latest version released did not have types, oddly `pnpm run build:types` did not emit any types when using `declarationDir`, I'm not sure if there's an obscure interaction going on between all the CLI flags but it works when using `outDir`.

Fix type exports build

---

README.md
site/docs/actions/public/L1/simulateProveWithdrawalTransaction.md
site/docs/actions/wallet/L1/writeDepositTransaction.md
site/docs/examples.md
site/index.md

Removes remaining references to the old l2Chain API from documentation.

Remove stray references to the old l2chain API

---

.changeset/grumpy-humans-protect.md
site/docs/actions/public/L1/simulateDepositETH.md
site/docs/actions/wallet/L1/writeDepositETH.md
site/docs/actions/wallet/L1/writeDepositTransaction.md
site/docs/actions/wallet/L1/writeFinalizeWithdrawalTransaction.md
src/_test/live.test.ts
src/actions/public/L1/getSecondsToNextL2Output.ts
src/actions/public/L1/simulateDepositETH.test.ts
src/actions/public/L1/simulateDepositETH.ts
src/actions/wallet/L1/writeDepositETH.test.ts
src/actions/wallet/L1/writeDepositETH.ts
src/actions/wallet/L1/writeDepositTransaction.test.ts
src/actions/wallet/L1/writeDepositTransaction.ts
src/actions/wallet/L1/writeFinalizeWithdrawalTransaction.test.ts
src/actions/wallet/L1/writeFinalizeWithdrawalTransaction.ts
src/types/depositETH.ts
vitest.config.ts

Addresses:
https://github.com/base-org/op-viem/issues/122
https://github.com/base-org/op-viem/issues/90
https://github.com/base-org/op-viem/issues/136

Api updates

---

.github/workflows/release.yml

Last pr https://github.com/base-org/op-viem/pull/158 there was a line of config that got missed when deleting prerelease code

👷 chore: Remove prerelease workflow follow up

---

.changeset/honest-mails-check.md
src/_test/constants.ts
src/actions/index.ts
src/actions/public/L1/getLatestProposedL2BlockNumber.test.ts
src/actions/public/L1/getSecondsToNextL2Output.test.ts
src/actions/public/L2/getProveWithdrawalTransactionArgs.test.ts
src/decorators/publicL1OpStackActions.ts
src/decorators/publicL2OpStackActions.ts
src/decorators/walletL1OpStackActions.ts
src/decorators/walletL2OpStackActions.ts
src/index.ts
src/utils/index.ts

We didn't export `getLatestProposedL2BlockNumber` among other things. Sorted all exports to make problems like this easier to spot in the future.

Ensure export coverage

---

dprint.json

The CHANGELOG has its own _valid_ and hard to configure way of formatting things which disagrees with dprint and breaks our release pipeline, so we'll ignore it.

Ignore changelog when formatting

---

site/.vitepress/config.mts
site/docs/actions/public/L2/estimateFees.md
site/docs/actions/public/L2/estimateL1Fee.md
site/docs/actions/public/L2/estimateL1GasUsed.md

Add documentation for `estimateFees`, `estimateL1Fee`, and `estimateL1GasUsed`.
Fixes #137.

Add documentation for gas estimation actions

---

src/_test/constants.ts

Without this change, running the tests on a fresh checkout results in many failed tests with the following error repeated in the output:
```
Error: Anvil exited: thread 'main' panicked at /home/runner/work/foundry/foundry/crates/anvil/src/eth/backend/mem/mod.rs:238:39:
Failed to create genesis: GetAccount(0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266, (code: -32000, message: missing trie node 6be1147a8f956737d61a31ba05c807d2820b1559f30ca027abcc2dd5badbc544 (path ) state 0x6be1147a8f956737d61a31ba05c807d2820b1559f30ca027abcc2dd5badbc544 is not available, data: None)
```
Setting `VITE_ANVIL_FORK_URL` to point to an RPC from an Infura account resolves the issue, presumably because the current default, `https://ethereum.publicnode.com` is probably not an archive node. `viem` itself [falls back …

Update the fallback anvil fork URL to use Cloudflare like viem does

---

site/docs/utilities/deposits/getL2HashFromL1DepositInfo.md
site/docs/utilities/transactionHelpers/getArgsFromTransactionDepositedOpaqueData.md
site/docs/utilities/transactionHelpers/transactionSerializer.md
site/docs/utilities/withdrawals/getProof.md

Still learning this codebase so let me know if any changes are needed :)

Added docs for getProof, transactionSerializer, and getArgsFromTransactionDepositedOpaqueData.
